### ISSUE TITLE
502 Proxy Error trying to post a question

### ISSUE THREAD

**Issue by jericson** [jbis9051/Socratic-Answers#2]
So I might have been testing really long tags and more than five in my first attempt to post a question. Perhaps for that reason I got a 502 Proxy Error:

> # Proxy Error
>
> The proxy server received an invalid response from an upstream server.  
> The proxy server could not handle the request [_POST /questions/ask_](https://code.socraticanswers.com/questions/ask).
>
> Reason: **Error reading from remote server**

I don't have a copy of my draft post, but pushing the limits on tag count and length seem likely culprits.

**Comment by jbis9051** [comment]
Thanks for reporting this :)
