### ISSUE TITLE
illegal chars

### ISSUE THREAD

**Issue by gewure** [jbis9051/Socratic-Answers#3]
![illegalchars](https://user-images.githubusercontent.com/5821352/75203772-5eb30b80-576f-11ea-9964-c84da817dca4.png)

check out how in the tags ´´ and `` is not recognized

**Comment by jbis9051** [comment]
Another issue is that you can paste illegal characters but you can't type them

**Comment by Ferynix** [comment]
theres an onpaste event, I used this plus onkeydown/onkeyup and also drag/drop events.

That way it updates EVERY change and moderates it completely

**Comment by jbis9051** [comment]
Created a new issue for the backticks. The google font as an issue, we will have to change.
