### ISSUE TITLE
Inputs are off center, Signup input is shrunk - Width Issues

### ISSUE THREAD

**Issue by Ferynix** [jbis9051/Socratic-Answers#5]
The inputs in the Profile page and Signup page are both off center, floating upwards **(This was fixed)**

The other issue is, the signup input checkbox for "opting in" to updates is very small, around 3px by 3px.

**So far this issue only occurs on chrome**

Solved this by disabling all width styles and setting the width to 60px as a temporary fix for chrome.

![Capture](https://user-images.githubusercontent.com/44554976/75588935-a07dd380-5a47-11ea-8d35-0a350f941406.PNG)

See below.

if all width is removed via inspect, it seems to create an invisible UV Model and places whitespace on the right side of the box:

![Capture](https://user-images.githubusercontent.com/44554976/75588862-7d532400-5a47-11ea-8813-fe36b75b9ac8.PNG)

Solved by:

![Capture](https://user-images.githubusercontent.com/44554976/75588653-1c2b5080-5a47-11ea-9ef9-093113bf5f0f.PNG)

**Comment by Ferynix** [comment]
EDIT: 50px doesnt cause whitespace issues, use that instead

**Comment by jbis9051** [comment]
Added custom checkboxes to todo
